# Git aliases
alias 'gc=git commit'
alias 'gcm=git commit -m'
alias 'ga=git add -A'
alias 'gap=git add -p'
alias 'gcp=git checkout -p'
alias 'gacm=ga; gcm'
alias 'gstat=git status'
alias 'gdiffc=git diff --cached'
alias 'gdiff=git diff'